version: "3.8"

networks:
  LabNetwork:
    external: true
  adminer:
    external: true

services:
  server:
    image: nginx
    restart: always
    env_file: env
    volumes:
      - ./nginx/in-vhost.conf:/etc/nginx/conf.d/in-vhost.conf:ro
      - ./app/public:/var/www/app/public:ro
    depends_on:
      - invoiceninja
    expose:
      - 80
    networks:
      - default
      - LabNetwork
    labels:
      traefik.enable: true
      traefik.http.routers.invoice.entrypoints: https
      traefik.http.routers.invoice.rule: Host(`invoice.domain.tld`)
      traefik.http.routers.invoice.tls: true
      traefik.http.routers.invoice.middlewares: security@file
      traefik.http.services.invoice.loadbalancer.server.port: 80

  invoiceninja:
    image: invoiceninja/invoiceninja:5
    restart: always
    volumes:
      - ./app/public:/var/www/app/public
      - ./app/storage:/var/www/app/storage
    depends_on:
      - db
    networks:
      - default
    expose:
      - 9000
    env_file: env

  db:
    image: mysql:5
    expose:
      - 3306
    restart: always
    env_file: env
    networks:
      - default
      - adminer
    volumes:
      - ./mysql/data:/var/lib/mysql
