version: "3.8"

networks:
  LabNetwork:
    external: true

services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    volumes:
      - ./minecraft_snapshot:/data
    networks:
      - default
    ports:
      - 25565:25565
    restart: unless-stopped
    environment:
      - EULA=TRUE
      - VERSION=SNAPSHOT
      - MEMORY=8G
