version: "3.8"

networks:
  LabNetwork:
    external: true
  adminer:
      external: true

services:
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - ./code:/home/coder
    expose: 
      - 8080
    networks:
      - default
      - LabNetwork
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.code-server.entrypoints: https
      traefik.http.routers.code-server.rule: Host(`code.domain.tld`)
      traefik.http.routers.code-server.tls: true
      traefik.http.routers.code-server.middlewares: security-auth@file
      traefik.http.services.code-server.loadbalancer.server.port: 8080

  jetbrains-projector:
    image: registry.jetbrains.team/p/prj/containers/projector-idea-u
    container_name: IntelliJ-Idea-Ultimate
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - ./idea:/home/projector-user
    expose: 
      - 8887
    networks:
      - default
      - LabNetwork
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.idea-server.entrypoints: https
      traefik.http.routers.idea-server.rule: Host(`idea.domain.tld`)
      traefik.http.routers.idea-server.tls: true
      traefik.http.routers.idea-server.middlewares: security-auth@file
      traefik.http.services.idea-server.loadbalancer.server.port: 8887

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - DB_HOST=postgres:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
    restart: unless-stopped
    networks:
      - default
      - LabNetwork
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "222:22"
    expose:
      - 3000
    depends_on:
      - postgres
    labels:
      traefik.enable: true
      traefik.http.routers.gitea.entrypoints: https
      traefik.http.routers.gitea.rule: Host(`git.domain.tld`)
      traefik.http.routers.gitea.tls: true
      traefik.http.routers.gitea.middlewares: security@file
      traefik.http.services.gitea.loadbalancer.server.port: 3000

  postgres:
    image: postgres:9.6
    restart: unless-stopped
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - default
      - adminer
    volumes:
      - ./postgres:/var/lib/postgresql/data