version: "3.8"

networks:
  LabNetwork:
    external: true

services:
  tracker-redis:
    image: redis:alpine
    container_name: tracker-redis
    volumes:
      - ./redis:/data
    networks:
      - default
    expose:
      - 6379
    restart: unless-stopped
    environment:
      - TZ=Europe/Lisbon

  chihaya:
    image: zmiguel/chihaya-redis-fix:latest
    container_name: chihaya
    volumes:
      - ./config-udp.yaml:/etc/chihaya.yaml:ro
    networks:
      - default
    expose:
      - 6880
    ports:
      - "1337:1337/udp"
    depends_on:
      - tracker-redis
    restart: unless-stopped
    environment:
      - TZ=Europe/Lisbon
      
  tracker-prometheus:
    image: prom/prometheus:latest
    container_name: tracker-prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/etc/prometheus'
    expose:
      - 9090
    networks:
      - default
      - LabNetwork
    restart: unless-stopped
