version: "3.8"

networks:
  LabNetwork:
    external: true

services:
  tracker-redis:
    image: redis:alpine
    container_name: tracker-redis
    volumes:
      - ./redis:/data
    networks:
      - default
    expose:
      - 6379
    restart: always
    environment:
      - TZ=Europe/Lisbon

  chihaya:
    image: zmiguel/chihaya-redis-fix:latest
    #container_name: chihaya
    volumes:
      - ./config.yaml:/etc/chihaya.yaml:ro
    networks:
      - default
      - LabNetwork
    labels:
      traefik.enable: true
      traefik.http.routers.chihaya.rule: Host(`tracker.domain.tld`)
      traefik.http.routers.chihaya.entrypoints: https
      traefik.http.routers.chihaya.tls: true
      traefik.http.routers.chihaya.middlewares: security@file
      traefik.http.services.chihaya.loadbalancer.server.port: 6969
    expose:
      - 6969
      - 6880
    depends_on:
      - tracker-redis
    restart: always
    environment:
      - TZ=Europe/Lisbon
    deploy:
      mode: replicated
      replicas: 10
      
  tracker-prometheus:
    image: prom/prometheus:latest
    container_name: tracker-prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/etc/prometheus'
    expose:
      - 9090
    networks:
      - default
      - LabNetwork
    restart: always
