version: "3.8"

networks:
  LabNetwork:
    external: true
  adminer:
      external: true

services:
  xbb:
    image: pe46dro/xbackbone-docker:latest
    container_name: xbb
    restart: always
    environment:
      - TZ=Europe/Lisbon
      - PUID=1000
      - PGID=1000
      - APP_NAME=OxedShare
      - URL=https://share.domain.tld
      - PHP_UPLOAD_MAX_FILESIZE=16G
      - PHP_POST_MAX_SIZE=16G
    expose:
      - '80'
    networks:
      - default
      - LabNetwork
    depends_on:
      - "xbb-db"
    volumes:
      - ./xbb/storage:/app/storage
      - ./xbb/database:/app/resources/database
      - ./xbb/logs:/app/logs
      - ./xbb/config:/app/config
    labels:
      traefik.enable: true
      traefik.http.routers.sharex.entrypoints: https
      traefik.http.routers.sharex.rule: Host(`share.domain.tld`)
      traefik.http.routers.sharex.tls: true
      traefik.http.routers.sharex.middlewares: security@file
      traefik.http.services.sharex.loadbalancer.server.port: 80

  xbb-db:
    image: mysql:5.7
    container_name: xbb-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: xbbrootpassword
      MYSQL_DATABASE: xbb
      MYSQL_USER: xbb
      MYSQL_PASSWORD: xbbpassword
    expose:
      - '3306'
    volumes:
      - ./xbb_mariadb:/var/lib/mysql
    networks:
      - default
      - LabNetwork
      - adminer

  ghost:
    image: ghost:alpine
    container_name: ghost_blog
    restart: always
    expose:
      - 2368
    networks:
      - default
      - LabNetwork
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      database__client: mysql
      database__connection__host: ghost_db
      database__connection__user: ghost
      database__connection__password: ghostpassword
      database__connection__database: ghost
      url: https://domain.tld/
    volumes:
      - ./ghost:/var/lib/ghost/content
    depends_on: 
      - ghost_db
    labels:
      traefik.enable: true
      traefik.http.routers.ghost.entrypoints: https
      traefik.http.routers.ghost.rule: Host(`domain.tld`,`www.domain.tld`)
      traefik.http.routers.ghost.tls: true
      traefik.http.routers.ghost.middlewares: security@file
      traefik.http.services.ghost.loadbalancer.server.port: 2368

  ghost_db:  
    image: mysql:5.7
    container_name: ghost_db
    volumes:
      - ./ghost/db:/var/lib/mysql
    restart: always
    networks:
      - default
      - adminer
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghostpassword

  grocy:
    image: ghcr.io/linuxserver/grocy:latest
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - ./grocy:/config
    expose:
      - 80
    networks:
      - default
      - LabNetwork
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.grocy.entrypoints: https
      traefik.http.routers.grocy.rule: Host(`grocy.domain.tld`)
      traefik.http.routers.grocy.tls: true
      traefik.http.routers.grocy.middlewares: security@file
      traefik.http.services.grocy.loadbalancer.server.port: 80

  web_mysql:
    image: mysql:5.7
    container_name: web_mysql
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    networks:
      - default
      - adminer
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bookstack
      MYSQL_USER: web_mysql
      MYSQL_PASSWORD: mysqlpassword

  bookstack:
    image: ghcr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://docs.domain.tld/
      - DB_HOST=web_mysql
      - DB_USER=web_mysql
      - DB_PASS=mysqlpassword
      - DB_DATABASE=bookstack
    networks:
      - default
      - LabNetwork
    volumes:
      - ./bookstack:/config
    expose:
      - 80
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.bookstack.entrypoints: https
      traefik.http.routers.bookstack.rule: Host(`docs.domain.tld`)
      traefik.http.routers.bookstack.tls: true
      traefik.http.routers.bookstack.middlewares: security@file
      traefik.http.services.bookstack.loadbalancer.server.port: 80

  planka:
    image: meltyshev/planka:latest
    container_name: planka
    command: >
      bash -c
        "for i in `seq 1 30`; do
          ./start.sh &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 seconds...\";
          sleep 5;
        done; (exit $$s)"
    restart: unless-stopped
    volumes:
      - ./board/user-avatars:/app/public/user-avatars
      - ./board/project-background-images:/app/public/project-background-images
      - ./board/attachments:/app/public/attachments
    networks:
      - default
      - LabNetwork
    expose:
      - 1337
    environment:
      - BASE_URL=https://board.domain.tld
      - DATABASE_URL=postgresql://postgres@postgres-board/planka
      - SECRET_KEY=12431d569c99380a413458ee1e379e14d57f12de26609663e6640a2f12dfac2f6aa1951a72a95ca1cdf94dce3643f64f3491e971f833c954b10cc2d075281ac9
    depends_on:
      - postgres-board
    labels:
      traefik.enable: true
      traefik.http.routers.board.entrypoints: https
      traefik.http.routers.board.rule: Host(`board.domain.tld`)
      traefik.http.routers.board.tls: true
      traefik.http.routers.board.middlewares: security-auth@file
      traefik.http.services.board.loadbalancer.server.port: 1337

  postgres-board:
    image: postgres:alpine
    container_name: postgres-board
    restart: unless-stopped
    networks:
      - default
      - adminer
    volumes:
      - ./board/db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=planka
      - POSTGRES_HOST_AUTH_METHOD=trust

  flame:
    image: pawelmalak/flame:latest
    container_name: flame
    environment:
      - TZ=Europe/Lisbon
    expose:
      - 5005
    networks:
      - default
      - LabNetwork
    volumes:
      - ./flame:/app/data
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.flame.entrypoints: https
      traefik.http.routers.flame.rule: Host(`flame.domain.tld`)
      traefik.http.routers.flame.tls: true
      traefik.http.routers.flame.middlewares: security@file
      traefik.http.services.flame.loadbalancer.server.port: 5005
